### ISSUE TITLE
Guava Collection Transformers

### ISSUE THREAD

**Issue by thomasnield** [ReactiveX/RxJavaGuava#17]
Would it make sense if I create a PR bringing in Google Guava collection Transformers? Or is the vision for this project to only interop with `ListenableFuture`? 

Here is the start of my Transformer library here
https://github.com/thomasnield/rx-guava/blob/master/src/main/java/org/nield/rx/guava/RxGuava.java

**Comment by abersnaze** [comment]
I'd be open to taking that in to this library.  I would like to keep this project java 6 compatible like RxJava is for android users.

**Comment by thomasnield** [comment]
grrr.. no lambdas?! Okay. I'll make sure my PR uses anonymous types.

**Comment by thomasnield** [comment]
Okay submitted a PR. Let me know if you have any suggestions.

**Comment by abersnaze** [comment]
I'll check it out in a bit

**Comment by abersnaze** [comment]
thanks for the PR.

**Comment by thomasnield** [comment]
No thank you! I'll implement some more collection transformers when I get a moment in the coming weeks.
